# Numpy

https://numpy.org/

## What is it? 
- Numpy is a Python library used for working with arrays
- Numpy is the fundamental package for scientific computing in Python


## Why do we care? 
- Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
- Super fast. Numpy arrays are implemented in C, which makes numpy very fast.
- The arrays allows for vectorized operations

## Show us! 

### Create a 1D array

#### create a list
format: list()

In [4]:
#create a list
my_list = ([1,2,3,4])

In [438]:
#whats the type


In [459]:
#what is dtype


In [460]:
#whats the shape


#### create an array
format: np.array()

In [10]:
#import numpy
import numpy as np

In [6]:
#create the array
my_array = np.array(my_list)

In [7]:
#whats the type
type(my_array)

numpy.ndarray

In [8]:
#whats the shape
my_array.shape

(4,)

#### access elements of our new array

In [9]:
my_array

array([1, 2, 3, 4])

In [10]:
my_array[0]

1

In [11]:
my_array[-1]

4

#### slice the array

In [12]:
my_array[1:] # inclusive for the first element

array([2, 3, 4])

In [13]:
my_array[:2]

array([1, 2])

#### create an array from 1 to 100

In [15]:
#np.array(?)
a = np.array(range(1,101))

In [17]:
#access single element
a[0]

1

In [18]:
#slice the array! 
a[25:]

array([ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

### Create a 2D array

In [20]:
#build a list of lists
matrix = [[1,2,3],
  [2,3,4],
  [6,7,8]]

In [21]:
type(matrix)

list

In [22]:
#turn it into an array! 
matrix_array = np.array(matrix)

In [23]:
#type
type(matrix_array)

numpy.ndarray

#### access elements

In [24]:
matrix_array[0]

array([1, 2, 3])

### Descriptive Stats

In [25]:
a.min()

1

#### using methods: the method is called on the numpy object

In [26]:
a.min()

1

In [27]:
a.max()

100

In [29]:
a.mean(), a.std()

(50.5, 28.86607004772212)

In [31]:
a.sum()

5050

In [213]:
np.max(a)

100

In [214]:
np.std(a)

28.86607004772212

In [215]:
np.mean(a)

50.5

In [216]:
np.sum(a)

5050

In [32]:
max(a)

100

In [33]:
min(a)

1

In [35]:
sum(a)

5050

#### using functions: using numpy to call functions

### Array of Booleans! 

### Boolean Masks

1. create an array
2. make a list of booleans (mask)
3. combine

    format: array [ list of booleans ] 

In [36]:
#pull back our small array
my_array

array([1, 2, 3, 4])

In [37]:
#make list of booleans aka our mask
mask = [True,False,False,True]
mask 

[True, False, False, True]

#combine them 
``` python
my_array[mask]
```

> only returns values that are true. This is known as boolean masking 

#### how else can we get our array of boolean values?

In [39]:
my_array

array([1, 2, 3, 4])

In [40]:
#write a conditional with the array
my_array == 4

array([False, False, False,  True])

#### make and apply our boolean mask

array([False, False, False,  True, False])

In [485]:
#format: array_name [ list_of_booleans ]


#### cool! can we just do it with a list instead of an array?

In [5]:
#pull back our initial list
my_list

[1, 2, 3, 4]

In [43]:
#create a array of booleans
my_list == 4

False

In [44]:
#apply an array of booleans to a list
my_list[mask]

TypeError: list indices must be integers or slices, not list

#### let's bring it back to arrays and make them bigger

In [45]:
#array
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [49]:
#mask
mask = a >= 90
mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [50]:
#boolean mask
a[mask]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### shortcut?

In [51]:
a [a >= 90]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### what if we wanted to check two conditions?

In [53]:
# note the parenthesis
# also note that we're using & instead of and
mask = (a > 5) & (a < 15) 

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

#### what if we wanted the opposite of our mask?

In [54]:
~mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [493]:
# the ~ notates the opposite of


## Vectorization Operations
- makes looping over math so easy and fast!

### Add one to every element

#### hard way: doing it in a list

In [3]:
my_list

NameError: name 'my_list' is not defined

In [7]:
#using a for loop
new_list = []
for x in my_list:
    new_list.append(x+1) 
print(new_list)

[2, 3, 4, 5]


In [ ]:
#using a list comprehension


#### easy way: doing it with an array

In [ ]:
#using vectorization operations


### more operations

### show us the speed

In [12]:
#make a really big array
big_array = np.array(range(1_000_001))
big_array

array([      0,       1,       2, ...,  999998,  999999, 1000000])

In [16]:
%%timeit

big_array ** 2

300 µs ± 3.37 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [503]:
#make a really big list


In [504]:
# %%timeit


## Numpy ways to create arrays


#### full of zeros

In [18]:
np.zeros(10,)


TypeError: Cannot interpret '2' as a data type

#### full of ones

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#### full of whatever you want 

In [27]:
np.full(100, 50)


TypeError: Cannot interpret '3' as a data type

#### a quicker way to make a range

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### an array of random integers

In [30]:
np.random.randint(2,20,10)


array([15,  5, 14,  7, 15, 13,  6, 17,  3, 13])

#### an array of random numbers from the standard distribution

In [31]:
np.random.randn()


-1.1022487022880536